[build]
builder = "nixpacks"
buildCommand = "npm run build:api"

[deploy]
startCommand = "node dist/apps/api/main.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
