[build]
builder = "nixpacks"
buildCommand = "npm ci && npx prisma generate && npm run build:production"

[deploy]
startCommand = "npx prisma migrate deploy && npm run start"
healthcheckPath = "/api/v1/info"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
